# Generated by Django 2.0.4 on 2018-05-15 01:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pickup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameday',
            name='anonymous_attendees',
        ),
        migrations.AddField(
            model_name='gameday',
            name='non_attendees',
            field=models.ManyToManyField(blank=True, related_name='_gameday_non_attendees_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gameday',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='_gameday_attendees_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
